---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: snapshot-push-credential
  namespace: showcase
spec:
  encryptedData:
    ssh-privatekey: AgBPu6m6Ol7B1R4Wcq4cR7mWzUXFOxJZY6SrMXG3Z2vZ8hRgzV4qM9O/NMJ1cBTKggcxiHqHY7OeDdHZDMTI3SeMNrGUBKWgORbQx0t3TZtbYvqyyAwHCScUIvdMiu04+7xIn4LHRrluCYYnevKQ1OtMGyBKMAECNvpvQ89Zy2tDFe2eoJbgZCBfMVVe1kDFJQWkol8lNbW+LqdW0357EqiWUMrMyAGUFBIYy4Fo2xF6Hq6frkGAyMohSiW6qVsoceF8Qn6j5vzAwoddOjoNwbixa++L/ey06KjNpe5rMMfUwQwAXfEG9iFePAbCDBsB5CVowTtZTQE3QU3fs9dYpyppOhn9gQGuHMBVorZsqGB1zDwMJP/+cQzjgNNf+bFP+MSdSnel4M7xWlUyAc5DVqslR0W+L0mvaXDdciYgpH8kXHiyOSAfDiZUOAKTeNiCZ1DByKCR1Mbp4fXNIlmbecj5wfZTCUQMSvYk/w9IWxfZy44JFYeUH11tXRa4p02rY8avAecsMUVRyVmLaSaeRP++lkx88WEBIG4aMwJQA22q34tbvWpltNdKYsDine2+ctnqQt6EcR2FeL47NOZvzpVnbOeJRvdfAXNmZ8jD91PkJdAbAYNRec/7WcBSvzmxWgM+EElwBGDEPRPXBGooqu4tAS8k9opj8A2LUDDVIVAiQhbsRLl7BmVNh7gZ9ca51lcUpcqf+Dl8Hxl7m69gJlcaSwYO3G5HPv7YB3PzD6nLdcqXXAQpsKByq/Ae7zP4G+lIbq2M2hS/QB145cxJ+Ekd2u2MuUH9ygdiIy0HP8kVwfKYcFP7bCWsqnCAwrERyaXIUVfcwVlFp0UgLZRceyM/tMfHKcOHWCaBEPEuyo8ubYWdqR2CscEU0euBc7uIteJWcxvK4yKEKNJ7l0qDyoYkJwpeYT+WjmBfTV9L95F6M8J0piNXkQXKmYRrzKx/UHpVoXVpgG7H9JIGEl/M9/rg5AdFQb2NjWs+9uVnPxZz+BnJkV5R3UFFNGzrQ5bMGW6Uf3a2lWPBpD9RL7aBvfh34aOCNhnBs6sIABTwk/AIkyGkJOiNuWPkatqZ7MPT+NFAdL/uGcsAeKvOlBN2rc8IDV0c5STuzsl8yTDM2rbPlVLVwEymnG1FjdBhwwi2knul6f/7oHkoMEKgvIc5C44GVb1/FHtMeI4+Y0guqumO9XwHXw3DJLuihj/0a0lmrAyBFq0emorO6Ffs5ZsWC8MgwLPQEUXrCY9FamIt+uVb74jVOQ==
  template:
    metadata:
      name: snapshot-push-credential
      namespace: showcase
