apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps
  namespace: argocd
  labels:
    devata.pragalva.me/tier: platform
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 86.2.0 #tagged version
      helm:
        valueFiles:
          - $values/kubernetes/infra/observability/kps/values.yaml
    - repoURL: https://github.com/PragalvaXFREZ/lab.git
      targetRevision: feat/longhorn-velero
      ref: values
    - repoURL: https://github.com/PragalvaXFREZ/lab.git
      targetRevision: feat/longhorn-velero
      path: kubernetes/infra/observability/kps/secrets
    - repoURL: https://github.com/PragalvaXFREZ/lab.git
      targetRevision: feat/longhorn-velero
      path: kubernetes/infra/observability/kps/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
