apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    devata.pragalva.me/tier: platform
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 7.0.0
      helm:
        valueFiles:
          - $values/kubernetes/infra/observability/loki/values.yaml
    - repoURL: https://github.com/PragalvaXFREZ/lab.git
      targetRevision: feat/longhorn-velero
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
