apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  labels:
    devata.pragalva.me/tier: platform
spec:
  project: default
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: 11.4.0
      helm:
        valueFiles:
          - $values/kubernetes/infra/storage/velero/values.yaml
    - repoURL: https://github.com/PragalvaXFREZ/lab.git
      targetRevision: feat/longhorn-velero
      ref: values
    - repoURL: https://github.com/PragalvaXFREZ/lab.git
      targetRevision: feat/longhorn-velero
      path: kubernetes/infra/storage/velero/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
