apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    api-token: AgB57xCjbsTyDTriPlwC6NL9JBFv8sawoCkQQJSBbJ152BypLpGT1IPVhmpAKoCtiBiem9Zdi2hxjszT3QFLt6k1SiW61GJQzejXWEyinfeYrl3Yco6PxNMgJ2oT8Kicn/v7+WwjpUiXTjiWL2clA5uDW2o9PTL4envu7l2tlChP7Xoy2N+Du60LyOMk7ezc+ppUIcbp+LaxTcNtBYIL9FSfTlWA/Y+HNbj6zZNuhkJZqgiMcWJkxlFgfSJzcm3F9DzyUZd2nLPBH3Vi/EiGigHZuIHQMcOt/yY/gNDUfqGHNc3FurwKj+Ng4BmHk3PAPFKMZ3nLM8UXhUuR5VNwz0K0ohDJci2TWt2xtZVhFs0x+S2hvT2bjLKqwe9+xHORz01fIgCggOIDPfZNxKoiBRVzAoE8t/XaMRT86u4kBCUq3oT+4yckxdKa9HIykS/4rqjnY5k2zCrk8b9IJdnjii+uiNqoRUXBb2Tfz0/mgoEMgjfu2DXS+iAOsqnXFUK5V6l9qUwbsJ0VL0HfDdNOIf8aukw3J5Jijs3HwjI6E3FEQeB+xDp+KEFMmROg84ljuBNVRw1PFXZOae6XWB78iUD5/q734QCfc5Lx2Ax30skQ7STqk/3hvIQK2sEauJqEK3eX1ltKAZ3kyAmU+hTAF35E5bwId0Qcg88DNg+mNYwrbeuUKvKq1HCfIWw+kWwswqIpkWmSxnh1xjMaHkQBoBMt7Br3VbXOk63FZ+kWOEFKEadV0SxVVkEAw1oVOjnJgMx0F+vFcQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
