apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealed-secret.yaml
  - deployment.yaml
  - pod-disruption-budget.yaml
  - service.yaml
  - service-monitor.yaml
  - prometheus-rule.yaml
  - network-policy.yaml
