---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    token: AgC0sxirsCFQFPJ+j4Y5+MkHUbfC5Nsk2HEG4LdozD/Pu/LI5q8rh/1e6fXixUYckxoIPJfXCmwUlcHQeQCx6XCThMeoiKWyHjOEWgGo58p9jsFpDexONhq1+LRk/4K4wPvyTeOH1x7twLz2n5iSTzWcgOOaqPdYm+woE3sofBqC8PA4vxF3ERJ9OLJFQS3Bhi1yE1dc5NeOlHUxs+yH+Hel4KvpEFXD5aPBeuWCR+DPLdjDSxhexX9uJLlAxmneNGD71DpPyAw2ezngyOL6Bgsieid5mxSjhbPDgvDWs1piDsfilrwfyBaq21I1aF3VwJNUj/n8pcT4mWzCFwMdPkvUBK8oL3hl/SlCNSf/xB4BvYv+QfMpLuN76LIZnN9pS64xEMwfozmjWl16CvImQWv5OfuR/9UWJ2ek0tIZs+UpQL6AXYbthH3p41hosBH5hcL5MImdYY8WQiMPFXGkVD4M+ejq0ChvqTLM7sB5RLdGFHL7YTz+upJa8hD0n6ZU2P74bppd7VdYJQS0XInPjgnd4y+BtAyVFaE98szWTjp5PoTwaGj6om4z9SwyQGRRGfFcEyt+ur4C/3Ea1vFSDFmHq63hVynGnj/SRVyhSob34802dUznlwKf1VSo5rdPwoRwYIkR4nDlzYFCDoICwp2EEcKVLRLTy/bOUwBqiPm4yYA/+8twYoBhJraNyHrxfTM1fwSlI6qMGXSQ73e4NIW+Lgyb5MsEUBWC2WDO0Kux1unAsDzlYxMPjz1jvx0iuGEAco7UhtNp7660IhslbB5068NVyo6SQGnOOkDcxx0rOLJidhVfljWiTNmxJsJg/dvxHsyYKB2PipqzaAxNeEiTWDfyOUwztUG93G6l8ruA7qb6dL10Oi6rq4xdgw8kb6U9sH6WYB0dpRSF9o8xcOG+OeiatKAc1pWthHO68cRmzFg8LiQAr68f
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflare-tunnel
