---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAa4RnkybKsp0i/MZCh+Qb2LhLAZrmZK4AL9VWUfpT9SPS2q8+ntX+pUX92lTZZkmfOP1L5wgxxo/J8inxnZj2DjffQWILuf+LIY4KfbHTbZ1DXZANlJdzIZBnT+TSTdKtdPpGeKvS63ZC+LTSfxk/SMyxqHYUMj7WgVDe0VcvP10Xk/4CviT0T144P0kpqwnaXyc2NCg6DQogwWLccWSG4X8rfvLqYlYyL6ofNe4/c8ZrGmi7d1JT8DiGnOOkEqcHr9XFdBoBR23my6FVkHccat4zvDjcp2jZjECCXIuN0yLeilC482ozcLFu30KwezIEzhY1Pa5N0rB4W+d7HeZEH1AMuP9CfWRJGntiB7WQHxd0EN94CKCxyqU0KkNwHOFWO/YV6DqvSZNOZ7uPmL3J7a+8MvZ3NOgd3XtxHnTYJsHMRSVjJCYtOu7zthHKD1303MYWJC+FPywZPbwpkMLTOuaAQSwQPJIpIiDnIZ6PH4ePDxgnxyVTOycoC+gMhhla6wtllHiRFmmSrel+qZIuYp5mVsgyw8UgamdqhRqU24KhDEQcNuX7aG4GHPo9din2ATr+27TZ7EOVYX2oTUgq0yVmVZQQuebtlFihqTEY/Li5TQk69B0+8o+ZVZM4100CaRj4mW9xW1+SgbHJj5z4tlV+KDAsSNNibRj9JmZ1Y+3g27Fmj/AV8VLYdRO2A34tDUhm0ROK7i/PpzCOiHfRYJ3A+DMON
    admin-user: AgApRiOHSmDY0KpcR+Wt3Cv4St+1cj+184P2beu0HiXJ62igwY1VSk2hyccrcJKvnQc69NGGUnlBKS/JEikhARW0mwFf2MH+flbnTTXZhcOXFlIRqS6TiVqQkNgmYRk61HEim6zbUFcI/0BHFtlrfesBmSa7jZBOafr1k9b3IZjFl51KfLS4A7RMEXr6m5NsH+Q/9LnmXrLhV3+P31YM7NkdKkISJcLJNpNToyZkbWhGzjbWvtiHC3TvPvkZ2HFlhRbVhgvKaJFptH/G5JEl8zHqjFDS80J5J+oTffxSmpGWeltTBcoEjnbFaEYnkZJIknsuBjie0o/7vMLtpSH21+UZ2desH/YDQZqc9XN094SvF6/d7wKnmbNd4Bm7GfhkjlIN7GyjLRlyNAeP8F3Kl6igeT4XprutP4OdjDozQcOBldaDLSq7BmcNMAUmFwaY6RdWXXj2eNK5qjB4sHXlyIKVTMhmSxzUPuYXUvgyCIfjRTA/3lJSezDR2FshDXndd+dTII8iqYX2uK40qvIRvB/xSel7rcHYUU/Ml1RmFME2eB9/7g/B83AQFDnXJwjfc/g8Jv0wW/NG2IY1Ra7uDfU1cyFY+P+4Nh6wNxPpriVcKzNohSBT6k5hTPHJg8Kizpw1uJJsomd7pL5jFgKEcbLVTGJsTtqNzYSNfaOzt0APbcArjuVMEUm8Thx5uZyhqvVa1RRQOA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
