apiVersion: v1
kind: Pod
metadata:
  name: init-demo-2
spec:
  initContainers:
  - name: check-db-service
    image: busybox:1.35
    command:
      - sh
      - -c
      - |
        until until nc -z db 3306; do
          echo waiting for db service
          sleep 2
        done

  - name: check-myservice
    image: busybox:1.35
    command:
      - sh
      - -c
      - |
        until wget -qO- myservice:80; do
          echo waiting for myservice
          sleep 2
        done

  containers:
  - name: main-container
    image: busybox
    command: ["sleep", "3600"]

