apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kps-grafana-rollback
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
  volumeName: pvc-69620b76-1592-4c0f-a26f-1b72bef13e2d
