apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-longhorn-staging
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
