apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-kps-kube-prometheus-stack-prometheus-db-prometheus-kps-kube-prometheus-stack-prometheus-0
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeName: pvc-af819889-2270-4e21-9113-3bb7f00b2408
