apiVersion: v1
kind: Pod
metadata:
  name: prometheus-storage-copy
  namespace: monitoring
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: talos-opt-7040
  containers:
    - name: copy
      image: alpine:3.22
      command:
        - sh
        - -c
        - sleep 1d
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 512Mi
      volumeMounts:
        - name: source
          mountPath: /source
          readOnly: true
        - name: destination
          mountPath: /destination
  volumes:
    - name: source
      persistentVolumeClaim:
        claimName: prometheus-kps-kube-prometheus-stack-prometheus-db-prometheus-kps-kube-prometheus-stack-prometheus-0
    - name: destination
      persistentVolumeClaim:
        claimName: prometheus-longhorn-staging
