apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hubble-traffic-producer
  namespace: showcase
spec:
  encryptedData:
    token: AgCqAq9Za7IVvDtaCyrE3wtfj47UdTKA0Es/vTPkeFLyAi/U8+vkl9grfjy1Z4Mbz2sid2FmcGe33IIfePR+GJ/+pyw++uCRHtinN7CvL8y4uDBEkxqtzBl4y5kQb/peMll4GHdPzeiY3aBD7h0gKhXVPCzS1orHlHDitO95h8JFKrX5sqXb04ztNtLUlcfxNxwJ1dhmeNkKBlurTBUI4I0IH3OXN+iw7c6aPxZlM+xobTdbVk71a34ggq1nGVFlxlsAiURk14WzTQRX7nlTJM9kzGODsTbQ3Po5Q4r3BqIH5DhZoWeW4Phft6vkG9vp4vTGsJX/1rf2KyTzWVGR3Ef07dEGRByjU+99WJDTC6kH+H/EZBCCp9V+1UEJeHVzIJamYzgTZistro8SyGgMp0q4qTQbrA6RI+PXBvKsE/MOgWQpjsX9TW3H7fxiVyaleRByxWm82n3C6IO4EP8/MyscImiSkk357k9ILZfnAC2RVCfynqnIQD1iQTHCCBd01fErhm+1dWkqH9SlMvJO1SBFklFi+Tv8A1KStMoOdaBcDbUummYUV90zjJAjVTfoLBOJfN2rNNBzODADcudr0eD5pW/3gWTK6IMKQO/nri1Y/PW6yE2u8pCih+vj4H0JKdN7TFRyoRhqG0j4E3CKHJrmBTjj78cUuE2XFe67oiANOAQitBvLmkuqa6soxLmxSx4A3hlMzoks23+mNoOClJOrd/apa2OHCbC8eJb10SxmCeaDcNfaNyzzqAKhmqwqvg6AMwShtn5eODRFTphZKztR
  template:
    metadata:
      name: hubble-traffic-producer
      namespace: showcase
