apiVersion: batch/v1
kind: Job
metadata:
  name: nvidia-smi
spec:
  backoffLimit: 1
  template:
    spec:
      runtimeClassName: nvidia
      restartPolicy: Never
      containers:
        - name: nvidia-smi
          image: nvcr.io/nvidia/cuda:12.8.0-base-ubuntu24.04
          command: ["nvidia-smi"]
          resources:
            limits:
              nvidia.com/gpu: 1
