/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 23c4e62c4cf361ea152e874fd807ecba)
interface __BaseEnv_Env {
	ALLOWED_ORIGIN: "https://pragalva.me";
	TRAFFIC_RELAY: DurableObjectNamespace<import("./src/index").TrafficRelay>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "TrafficRelay";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
