apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
  labels:
    app: nginx-storage
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: scratch-volume
          mountPath: /scratch
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi

