apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgChcdrHMwdfen5UZ52581EP2dcEI7Kp7a++MGQjpSWXx7VVCg+fPcNwMoO88HbpnF4+m+5fR2UEuR6gaXleHylE+PDngkosZQs+SZeBlpOZ9VZM2OUxzmZoiEKnCScis9vfbwoVOvewNtLWzo+2sJl9S/y7I/R4z8BeZD4H7eHXI4bx3OpSHWQYxvllfZN3jfJ7XFZ/vAxzp2q/FUfbRrL9urEUrzGJvkJl8NtSnfRUVw3lHZrCXvKk6FX6yCescLigN3kTtUBa2wKzHxfihoNsnwrVX2OXK4o4TWSqFN243damCOuTencbqkcEcspM3aCc9xvOdBJcK1u9VQRKOsDQ3B5sEB+KI4UkEUzTOyPMlhdXqmBDWKgTUFUpmQaRXk2u2R0/Ql8cJt7Ys+x1diPpwtTfwXhzZnc4zTd2YwB+7m9f0sUAo6mWCdX6pErShln333ANmI3occsI16MfqRrlVassUHpuZyjwjbNq5r8tLOo0ccI+vdCqQOBuRZWBz7Ar32BOG5vVHjRouZfM6IiUhREPQU2Nj1O8k4Wh23toQcAHQJQxhsTP/XK8Hwp4PAajNAq6Dh1h9nCZnhAneV5lcs5RagGtt2oqVVX86daFf6ciO22OLuNk+T9Zutm2KHtZz/h7Rm5fXrJZ0gdHNvki7zhZ7wOyyjSwbuyOpaBDuZQ2js4d3OI0h6CbijkqfgxkW9Nf3hgLZqWGzIkbWvkkZ4Y0f7Gx/Qf6hX0vnG93VUKKv0XUbFqqp/ii5h1oUrnFyNTdCa6OQLr3d5kzpz0p1bEj6+R9q/64IhzLeGvBKg3jXDTOatol1+lBBk1PBMXgeB/Ys3BuVsKajOObhnw2m4jCRvC3VAf3GH0C4VBzq1YaeG5kpxorMtwNEaC2BMH+mqU7
  template:
    metadata:
      name: cloud-credentials
      namespace: velero
