---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgAAlyLjqRpUDt3omWbbdJMcEe/SnhA4mHi/MshN1+rnsUL+J6Ew0R+fjnZLJUjE7oJnXCd4Qv6/0hJgM6ZDvsCSERhVa1SBqshgklHB+ZzsYFplid4dNEX6U2hQsIxzdDntXAH7OGKpUsCRwfNmYj6fxMJ5EAeQWVJxSvCquTJgDWGc+4YhrrWoxvv3XqWo3Zn0s9ArDA9dQ9DFeeRZDycEpZ+Bz6/CQSKQSQlH7V2sSHKGSD/QHJ+Dt9yzMNXIO0NRHguCInlnGrh6/ZlVzdoHSGn6s0yb4/QGEvJVNmhol5io4CnBTgjMuAmuT126E8XKmk4EJhXViQe4mp8CGkj6E2XcZC3A4++53Q330iU/604CuAIecQtw4Z8RHy/VqIwRAPz2Sn3/GFXlRTBGGJtljro1RXPTiyeiLqdSRcJyKFqC6/Wbo14kowXKyPBAde/KpsHTIc/lGIjn+ttGm+DSpynEBnOteVKaJjQAXKmtudeDHbRx46r0x4XJvfcGjNYtzseuK1ZVPLiyYuVuisr+Nd7A72rSxehGA1+3nMoO6FKe6SKpc8/fF/9VoDMt75Z3B9hpBfDka5BOcNZygT4zH3tOFiNBoP2RRegH/poTAHtdLwyFc2t3p8buY6SZwg8DR30LQdU/CXDH6BKSkgMuSvPpd2f7iUI8mW9sToZcKzO5pIkZ+ygLxbeLx5rK3PUMKdG5YfJ5vohsTkr7oKrnAG5BlmdAARPEl5UPNEFZKLgrg4CLy664b0iDATMLCdBrtf/joeQxoe3nzB/M+gkW
  template:
    metadata:
      name: velero-repo-credentials
      namespace: velero
    type: Opaque
